#!/bin/zsh
#
# GREETER SCRIPT FOR ARCHLINUX SRV
#

#########################################
#
#		VARIABLES
#
#########################################

# Hostname
host="$(cat /etc/hostname)"

# Kernel information
kernel="$(uname -sr)"

# Uptime
uptime="$(uptime -p | sed 's/up //')"

# Numbers of packages installed
packages="$(pacman -Q | wc -l)"

# Numbers of updates pending
updates_count="$(checkupdates | wc -l)"

# Numbers of IP bannedi

f2b="$(sudo fail2ban-client status sshd | grep 'Currently banned' | rev | cut -f 1 | rev)"
banned="$f2b IP banned"		

# Text to be displayed
if (( $updates_count > 0 )); then
	updates="$updates_count updates pending"
else
	updates="$updates_count update pending" 
fi

## Filesystem
# Number of '-' to be displayed on the filesystem occupation
number=30

# /mnt/INT1
read int1_a int1_s int1_m int1_pcent<<< "$(df -h --output=avail,size,target,pcent /dev/sda2 | tail -1)" 

# /
read root_a root_s root_m root_pcent<<< "$(df -h --output=avail,size,target,pcent /dev/sdb7 | tail -1)"

# /boot
read boot_a boot_s boot_m boot_pcent<<< "$(df -h --output=avail,size,target,pcent /dev/sdb5 | tail -1)"

# /mnt/EXT1
read ext1_a ext1_s ext1_m ext1_pcent <<< "$(df -h --output=avail,size,target,pcent /dev/sdc1 | tail -1)"

# /mnt/EXT2
read ext2_a ext2_s ext2_m ext2_pcent <<< "$(df -h --output=avail,size,target,pcent /dev/sdd1 | tail -1)"



## Colors
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

beg="${c1} ${c0}"			# in front of information
c0="${reset}${blue}${bold}"		# logo + text 1 color
c1="${reset}${white}${bold}"		# text 2 color
upd_color=""				# updates based on amount

#########################################
#
#		FUNCTIONS
#
#########################################

# Displays a progression bar of the FS depending on the available space and the total space
# $PARAM1 = name of the FS
# $PARAM2 = available size
# $PARAM3 = total size
# $PARAM4 = percentage used
# $PARAM5 = Number of - to be displayed
trace_fs () {
	temp1="${4%?}"			# Remove last character
	temp2=$(($temp1*$5/100))	# Number of #
	str="["				# Initiate

	# Add a color to the output
	if (($temp1 > 75)); then
		str+="${red}"
	elif (($temp1 > 50)); then
		str+="${yellow}"
	elif (($temp1 > 25)); then
		str+="${green}"
	else 
		str+="${white}"
	fi
	# Fill with '#'
	for i in {1..$temp2}
	do
		str+="#"
	done

	# reset the color
	str+="${white}"

	# Fill with '-'
	for i in {$temp2..$5}
	do
		str+="-"
	done
	str+="]"
	echo $str
}

sda2=$(trace_fs $int1_m $int1_a $int1_s $int1_pcent $number)
sdb7=$(trace_fs $root_m $root_a $root_s $root_pcent $number)
sdb5=$(trace_fs $boot_m $boot_a $boot_s $boot_pcent $number)
sdc1=$(trace_fs $ext1_m $ext1_a $ext1_s $ext1_pcent $number)
sdd1=$(trace_fs $ext2_m $ext2_a $ext2_s $ext2_pcent $number)


#########################################
#
#		PROCESSING		
#
#########################################

# Setting updates color 
if (( $updates_count > 15 )); then
	upd_color="${reset}${red}"
elif (( $updates_count > 5 )); then
	upd_color="${reset}${yellow}"
else	
	upd_color="${reset}${white}"
fi

cat <<EOF
${c0}                    -\`
${c0}                   .o+\`			
${c0}                  \`ooo/			
${c0}                 \`+oooo:		${white}               #     ${blue}| *
${c0}                \`+oooooo:		${white} a##e #%" a#"e 6##%  ${blue}| | |-^-. |   | \\ /
${c0}                -+oooooo+:		${white}.oOo# #   #    #  #  ${blue}| | |   | |   |  X
${c0}             \`/:-:++oooo+:		${white}%OoO# #   %#e" #  #  ${blue}| | |   | ^._.| / \\ TM	
${c0}             \`/++++/+++++++:		${white}----------------------------------------	 	
${c0}            \`/++++++++++++++:		${beg}${USER}${reset}@${c0}${host}	
${c0}           \`/+++ooooooooooooo/\`		${beg}KERNEL:	${c1}${kernel}	
${c0}          ./ooosssso++osssssso+\`	${beg}UPTIME:	${c1}${uptime}
${c0}         .oossssso-\`\`\`\`/ossssss+\`	${beg}PACKAGES:	${c1}${packages}
${c0}        -osssssso.      :ssssssso.	${beg}UPDATES:	${upd_color}${updates}
${c0}       :osssssss/        osssso+++.	${beg}BANNED:	${c1}${banned}	 	
${c0}      /ossssssss/        +ssssooo/-
${c0}    \`/ossssso+/:-        -:/+osssso+-
${c0}   \`+sso+:-\`                 \`.-/+oso:
${c0}  \`++:.                           \`-/+/
${c0}  .\`                                 \`/
${white}${bold}--------------------------------------------------------------------------------
FILESYSTEM	TOTAL	AVAIL	USED	
$root_m		$root_s	$root_a	$root_pcent	${sdb7}
$boot_m		$boot_s	$boot_a	$boot_pcent	${sdb5}
$int1_m	$int1_s	$int1_a	$int1_pcent	${sda2}
$ext1_m	$ext1_s	$ext1_a	$ext1_pcent	${sdc1}
$ext2_m	$ext2_s	$ext2_a	$ext2_pcent	${sdd1}
${white}${bold}--------------------------------------------------------------------------------
EOF
