#!/bin/zsh


## FILESYSTEM
read sdb1_a sdb1_s sdb1_m <<< "$(df -h --output=avail,size,target /dev/sda1 | tail -1)" 

echo $sdb1_m mount
echo $sdb1_a avail 
echo $sdb1_s size


# Displays a progression bar of the FS depending on the available space and the total space
# $PARAM1 = name of the FS
# $PARAM2 = available size
# $PARAM3 = total size
trace_fs () {
	echo $sdb1_m "[#########-------------]" $sdb1_a / $sdb1_s	
}

trace_fs

## SERVICES
return 0
